# Generated by Django 4.1.4 on 2022-12-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_country_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=150, verbose_name='country'),
        ),
    ]
